"""
Django settings for ufk_testapp project.

Generated by 'django-admin startproject' using Django 1.8.

For more information on this file, see
https://docs.djangoproject.com/en/1.8/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.8/ref/settings/
"""

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
import os

import django

BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/1.8/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = "!u-4q!$+GO2_=!$p&0cr*57z1oN72sady26&8"

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = (
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    # the app that we are testing with
    "myapp",
)


MIDDLEWARE = MIDDLEWARE_CLASSES = (
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    # 'django.contrib.auth.middleware.SessionAuthenticationMiddleware',
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    "django.middleware.security.SecurityMiddleware",
)


ROOT_URLCONF = "cleanhtmlfield_testapp.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "ufk_testapp.wsgi.application"


# Database

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": os.path.join(BASE_DIR, "db.sqlite3"),
    }
}


# Internationalization
# https://docs.djangoproject.com/en/1.8/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/1.8/howto/static-files/

STATIC_URL = "/static/"


# HTMLField
# Acceptable html tags, attributes and styles. Others are removed before saving
# if the HTML field is marked as safe.
ACCEPTABLE_ELEMENTS = (
    "a",
    "abbr",
    "acronym",
    "address",
    "area",
    "aria-label",
    "b",
    "big",
    "blockquote",
    "br",
    "button",
    "caption",
    "center",
    "cite",
    "code",
    "col",
    "colgroup",
    "dd",
    "del",
    "dfn",
    "dir",
    "div",
    "dl",
    "dt",
    "em",
    "font",
    "h1",
    "h2",
    "h3",
    "h4",
    "h5",
    "h6",
    "hr",
    "i",
    "img",
    "ins",
    "kbd",
    "label",
    "legend",
    "li",
    "map",
    "menu",
    "ol",
    "p",
    "pre",
    "q",
    "s",
    "samp",
    "small",
    "span",
    "strike",
    "strong",
    "sub",
    "sup",
    "table",
    "tbody",
    "td",
    "tfoot",
    "th",
    "thead",
    "tr",
    "tt",
    "u",
    "ul",
    "var",
    "iframe",
    "section",
    "article",
)

ACCEPTABLE_ATTRIBUTES = (
    "abbr",
    "accept",
    "accesskey",
    "action",
    "align",
    "alt",
    "axis",
    "border",
    "cellpadding",
    "cellspacing",
    "char",
    "charoff",
    "charset",
    "checked",
    "cite",
    "class",
    "clear",
    "cols",
    "colspan",
    "color",
    "compact",
    "coords",
    "data-mlang",
    "data-equation",
    "datetime",
    "dir",
    "enctype",
    "for",
    "headers",
    "height",
    "href",
    "hreflang",
    "hspace",
    "id",
    "ismap",
    "label",
    "lang",
    "longdesc",
    "maxlength",
    "method",
    "multiple",
    "name",
    "nohref",
    "noshade",
    "nowrap",
    "prompt",
    "rel",
    "rev",
    "rows",
    "rowspan",
    "role",
    "rules",
    "scope",
    "shape",
    "size",
    "style",
    "span",
    "src",
    "start",
    "summary",
    "tabindex",
    "target",
    "title",
    "type",
    "usemap",
    "valign",
    "value",
    "vspace",
    "width",
)

ACCEPTABLE_STYLES = (
    "background-color",
    "background",
    "background-image",
    "background-position",
    "background-size",
    "background-repeat",
    "background-attachment",
    "background-origin",
    "background-clip",
    "font-family",
    "font-size",
    "font-weight",
    "font-style",
    "color",
    "width",
    "height",
    "min-width",
    "max-width",
    "min-height",
    "max-height",
    "line-height",
    "text-decoration",
    "text-transform",
    "text-align",
    "border",
    "border-style",
    "border-width",
    "border-top",
    "border-bottom",
    "border-left",
    "border-right",
    "border-top-style",
    "border-bottom-style",
    "border-left-style",
    "border-right-style",
    "border-top-width",
    "border-bottom-width",
    "border-left-width",
    "border-right-width",
    "border-color",
    "border-top-color",
    "border-bottom-color",
    "border-left-color",
    "border-spacing",
    "border-collapse",
    "border-right-color",
    "border-radius",
    "vertical-align",
    "clear",
    "float",
    "margin",
    "margin-left",
    "margin-right",
    "margin-top",
    "margin-bottom",
    "outline",
    "padding",
    "padding-left",
    "padding-right",
    "padding-top",
    "padding-bottom",
)

REMOVE_WITH_CONTENT = (
    "script",
    "object",
    "embed",
    "style",
    "form",
)

PRESERVE_STYLES_WHITESPACE = False
