# Generated by Django 2.0 on 2017-12-20 10:09

from django.db import migrations, models

import django_cleanhtmlfield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="MyModel",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "some_html_field",
                    django_cleanhtmlfield.fields.HTMLField(strip_unsafe=True),
                ),
            ],
        ),
    ]
